apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: guest-replica1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guest
  template:
    metadata:
      name: pod-guest
      labels:
        app: guest
    spec:
      containers:
      - name: container
        image: academyitwill/app:v1
      terminationGracePeriodSeconds: 0
---
apiVersion: v1
kind: Service
metadata:
  name: svc-guest
spec:
  selector:
    app: guest
  ports:
    port: 80
    targetPort: 80
    nodePort: 30001
  type: NodePort

