apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: guest-replica2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guest2
  template:
    metadata:
      name: pod-guest2
      labels:
        app: guest2
    spec:
      containers:
      - name: container
        image: academyitwill/guest:v2
        imagePullPolicy: Always
      terminationGracePeriodSeconds: 0
---

apiVersion: v1
kind: Service
metadata:
  name: svc-guest2
spec:
  selector:
    app: guest2
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002
  type: NodePort

