apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: guest-replica3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guest3
  template:
    metadata:
      name: pod-guest
      labels:
        app: guest3
    spec:
      containers:
      - name: container
        image: academyitwill/guest:v3
        env:
          - name: USER_PROFILE
            value: remote-oracle   # ← 여기서 "remote-oracle", "local-mysql", "prod-mysql" 등 지정
        imagePullPolicy: Always
      terminationGracePeriodSeconds: 0
---

apiVersion: v1
kind: Service
metadata:
  name: svc-guest3
spec:
  selector:
    app: guest3
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30003
  type: NodePort

