##### mysql-configmap.yaml #####
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
    grant all on guestdb.* to 'jdeveloper'@'%';
---
##### mysql-secret.yaml #####
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  #mysql-root-password: root
  #mysql-user-id: jdeveloper
  #mysql-user-password: jdeveloper
  #mysql-database-name: guestdb
  #https://www.base64encode.net/
  mysql-root-password: cm9vdA==
  mysql-user-id: amRldmVsb3Blcg==
  mysql-user-password: amRldmVsb3Blcg==
  mysql-database-name: Z3Vlc3RkYg==
---
##### mysql-pv.yaml #####
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mysql
---
##### mysql-pvc.yaml #####    
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
    
---
##### mysql-deployment.yaml #####    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql-pod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-pod
    spec:
      containers:
        - name: mysql-container
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root   # 보안을 위해 Secret 사용하는 것이 좋음
            - name: MYSQL_USER
              value: jdeveloper
            - name: MYSQL_PASSWORD
              value: jdeveloper
            - name: MYSQL_DATABASE
              value: guestdb  
          ports:
            - containerPort: 3306
              name: mysql-container
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d  
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: initdb
          configMap:
            name: mysql-initdb-config    
---
##### mysql-service.yaml #####   
# apiVersion: v1
# kind: Service
# metadata:
#   name: mysqlservice
# spec:
#   type: NodePort
#   ports:
#   - name: mysql-port
#     port: 3306
#     targetPort: 3306
#     nodePort: 30006
#   selector:
#     app: mysql-pod
apiVersion: v1
kind: Service
metadata:
  name: mysqlservice
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-pod
  clusterIP: None  # Headless로 할 경우 None (옵션)

